name: RIN
main: dev.angelsflyinhell.rin.RIN
author: angelsflyinhell
version: 1.1.0
api-version: 1.14
commands:
  sethome:
    description: Save your current location as a Home Point.
    usage: /<command> <name>
    aliases: [ sh, seth, shome ]
  delhome:
    description: Delete a Home Point from your Home Point list.
    usage: /<command> <name>
    aliases: [ dh, del0h, dhome ]
  homes:
    description: View a list of all Home Points owned by you.
    usage: /<command>
    aliases: [hs, hlist, homel]
  home:
    description: Select a Home Point to teleport to.
    usage: /<command> <name>
    aliases: [ h, hp, tpH, teleportH, tpHome ]